// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGx2HvfYvs0hx9FyMq3tJ-e5r7xpv53ww',
    appId: '1:595443785662:web:52512c4c1b4480f870a3ef',
    messagingSenderId: '595443785662',
    projectId: 'chat-app-cd59f',
    authDomain: 'chat-app-cd59f.firebaseapp.com',
    storageBucket: 'chat-app-cd59f.appspot.com',
    measurementId: 'G-G66ZC6RQXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBie62FP4VDKr02Shr4TZYLOqPItF5thNI',
    appId: '1:595443785662:android:c441ca96e812f29870a3ef',
    messagingSenderId: '595443785662',
    projectId: 'chat-app-cd59f',
    storageBucket: 'chat-app-cd59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1KSNPmbRDqjejQdW7kLBeAgFiSJla7I0',
    appId: '1:595443785662:ios:0a76f08adf8e31eb70a3ef',
    messagingSenderId: '595443785662',
    projectId: 'chat-app-cd59f',
    storageBucket: 'chat-app-cd59f.appspot.com',
    iosClientId: '595443785662-7jgqi5hs3tggmeofp6u0n906eqkcr60d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1KSNPmbRDqjejQdW7kLBeAgFiSJla7I0',
    appId: '1:595443785662:ios:0a76f08adf8e31eb70a3ef',
    messagingSenderId: '595443785662',
    projectId: 'chat-app-cd59f',
    storageBucket: 'chat-app-cd59f.appspot.com',
    iosClientId: '595443785662-7jgqi5hs3tggmeofp6u0n906eqkcr60d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
